import Link from "next/link";
import { createMajorError, reviewMajorError, savePayrollMonth } from "@/app/actions/people-finance";
import { AppShell, Notice, StatusBadge } from "@/components/app-shell";
import { requirePagePermission } from "@/lib/authorization";
import { canManageFinance, canManagePeople } from "@/lib/people-finance/access";
import { db } from "@/lib/db";

export const dynamic = "force-dynamic";

export default async function PayrollPage({ searchParams }: { searchParams: Promise<{ error?: string; success?: string }> }) {
  const actor = await requirePagePermission("finance:read"); const query = await searchParams; const financeManage = canManageFinance(actor); const peopleManage = canManagePeople(actor);
  const [employees, payroll, errors] = await Promise.all([
    db.employeeProfile.findMany({ where: { organizationId: actor.organizationId }, select: { id: true, employeeNo: true, member: { select: { user: { select: { name: true } } } }, compensation: true }, orderBy: { employeeNo: "asc" } }),
    db.payrollMonth.findMany({ where: { organizationId: actor.organizationId }, include: { employee: { select: { member: { select: { user: { select: { name: true } } } } } } }, orderBy: [{ year: "desc" }, { month: "desc" }], take: 100 }),
    db.majorError.findMany({ where: { organizationId: actor.organizationId }, include: { employee: { select: { member: { select: { user: { select: { name: true } } } } } } }, orderBy: { occurredOn: "desc" }, take: 50 }),
  ]);
  return <AppShell eyebrow="People & Finance" title="薪资绩效与重大错误"><Notice {...query} /><div className="subnav"><Link href="/people">员工</Link><Link href="/people/attendance">考勤异常</Link><Link href="/people/payroll">薪资绩效</Link></div>
    <section className="dashboard-grid"><div className="panel span-2"><h2>月度薪资</h2>{payroll.length === 0 ? <p className="empty-state">暂无薪资月记录。</p> : <div className="table-scroll"><table><thead><tr><th>月份 / 员工</th><th>基础</th><th>绩效</th><th>佣金</th><th>补贴</th><th>扣罚</th><th>实发</th></tr></thead><tbody>{payroll.map((p) => <tr key={p.id}><td>{p.year}-{String(p.month).padStart(2, "0")}<small className="cell-note">{p.employee.member.user.name}</small></td><td>{p.baseSalary.toFixed(2)}</td><td>{p.performance.toFixed(2)}</td><td>{p.commission.toFixed(2)}</td><td>{p.allowance.toFixed(2)}</td><td>{p.penalties.toFixed(2)}</td><td><strong>{p.netPay.toFixed(2)} {p.currency}</strong></td></tr>)}</tbody></table></div>}</div>{financeManage && <form action={savePayrollMonth} className="panel form-stack compact-form"><h2>保存月度薪资</h2><label>员工<select name="employeeId">{employees.map((e) => <option key={e.id} value={e.id}>{e.member.user.name}</option>)}</select></label><label>年份<input name="year" type="number" defaultValue={new Date().getFullYear()} /></label><label>月份<input name="month" type="number" min={1} max={12} defaultValue={new Date().getMonth() + 1} /></label><label>基础薪资<input name="baseSalary" inputMode="decimal" defaultValue="0.00" /></label><label>绩效<input name="performance" inputMode="decimal" defaultValue="0.00" /></label><label>佣金<input name="commission" inputMode="decimal" defaultValue="0.00" /></label><label>补贴<input name="allowance" inputMode="decimal" defaultValue="0.00" /></label><label>扣罚<input name="penalties" inputMode="decimal" defaultValue="0.00" /></label><label>币种<input name="currency" defaultValue="CNY" maxLength={3} /></label><label>备注<textarea name="note" /></label><button className="button-primary" type="submit">保存薪资</button></form>}</section>
    <section className="dashboard-grid mt-6"><div className="panel span-2"><h2>重大错误与扣罚</h2>{errors.length === 0 ? <p className="empty-state">暂无重大错误记录。</p> : <div className="record-stack">{errors.map((e) => <article className="record-row" key={e.id}><div><h3>{e.title}</h3><p>{e.employee.member.user.name} · {e.occurredOn.toLocaleDateString("zh-CN")}</p></div><div><StatusBadge>{e.status}</StatusBadge><strong>{e.penaltyAmount.toFixed(2)} 元</strong>{peopleManage && e.status === "REPORTED" && <form action={reviewMajorError} className="status-form"><input type="hidden" name="id" value={e.id} /><select name="to"><option value="CONFIRMED">确认</option><option value="DISMISSED">撤销</option></select><button className="button-secondary" type="submit">审核</button></form>}</div></article>)}</div>}</div>{peopleManage && <form action={createMajorError} className="panel form-stack compact-form"><h2>记录重大错误</h2><label>员工<select name="employeeId">{employees.map((e) => <option key={e.id} value={e.id}>{e.member.user.name}</option>)}</select></label><label>日期<input name="occurredOn" type="date" required /></label><label>标题<input name="title" required /></label><label>详情<textarea name="detail" /></label><label>扣罚金额<input name="penaltyAmount" inputMode="decimal" defaultValue="0.00" /></label><button className="button-secondary" type="submit">记录</button></form>}</section>
  </AppShell>;
}
