import Link from "next/link";
import { notFound } from "next/navigation";
import { changeLiveStatus, saveProductPerformance, saveSessionReview } from "@/app/actions/live-commerce";
import { AppShell, Notice, StatusBadge } from "@/components/app-shell";
import { requirePagePermission } from "@/lib/authorization";
import { db } from "@/lib/db";
import { derivePerformance } from "@/lib/live-commerce/metrics";
import { nextLiveStatuses } from "@/lib/live-commerce/state-machines";

export const dynamic = "force-dynamic";

export default async function LiveDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; success?: string }> }) {
  const member = await requirePagePermission(); const { id } = await params; const query = await searchParams;
  const [session, products] = await Promise.all([
    db.liveSession.findFirst({ where: { id, organizationId: member.organizationId }, include: {
      owner: { select: { user: { select: { name: true } } } }, staff: { include: { member: { select: { user: { select: { name: true } } } } } }, previews: { include: { content: { select: { id: true, title: true } } } }, statusHistory: { include: { actor: { select: { user: { select: { name: true } } } } }, orderBy: { createdAt: "desc" } }, productPerformance: { include: { product: { select: { name: true, currency: true } } }, orderBy: { updatedAt: "desc" } }, feedback: { where: { status: { not: "CLOSED" } }, orderBy: { createdAt: "desc" } },
    } }),
    db.commerceProduct.findMany({ where: { organizationId: member.organizationId, active: true }, select: { id: true, name: true }, orderBy: { name: "asc" } }),
  ]);
  if (!session) notFound();
  const nextStatuses = nextLiveStatuses(session.status);
  return <AppShell eyebrow="Live session" title={session.title}><Notice {...query} /><div className="subnav"><Link href="/live">返回场次</Link><Link href="/live/products">商品资料</Link><Link href="/live/feedback">客诉处理</Link></div>
    <section className="panel"><div className="detail-meta"><div><p>状态</p><StatusBadge>{session.status}</StatusBadge></div><div><p>负责人</p><strong>{session.owner.user.name}</strong></div><div><p>计划时间</p><strong>{session.startsAt.toLocaleString("zh-CN")}</strong></div><div><p>渠道</p><strong>{session.channel}</strong></div></div><p className="section-copy">人员：{session.staff.map((row) => `${row.member.user.name} (${row.role})`).join("、") || "未指定"}</p><p className="section-copy">预热视频：{session.previews.length ? session.previews.map((row) => <Link className="record-link" href={`/content/${row.content.id}`} key={row.contentId}>{row.content.title}</Link>) : "未关联"}</p>
      {nextStatuses.length > 0 && <form action={changeLiveStatus} className="status-form mt-6"><input type="hidden" name="id" value={session.id} /><label className="sr-only" htmlFor="live-status">下一状态</label><select id="live-status" name="to">{nextStatuses.map((status) => <option key={status}>{status}</option>)}</select><input name="note" placeholder="状态备注（可选）" /><button className="button-secondary" type="submit">更新状态</button></form>}
    </section>
    <section className="dashboard-grid mt-6"><div className="panel span-2"><h2>场次 × 商品表现</h2>{session.productPerformance.length === 0 ? <p className="empty-state">暂无商品表现。</p> : <div className="table-scroll"><table><thead><tr><th>商品</th><th>曝光 / 点击</th><th>订单 / 买家</th><th>GMV / 退款</th><th>点击率</th><th>转化率</th><th>退款率</th></tr></thead><tbody>{session.productPerformance.map((row) => { const rates = derivePerformance(row); return <tr key={row.id}><td>{row.product.name}</td><td>{row.impressions} / {row.clicks}</td><td>{row.orders} / {row.buyers}</td><td>{row.gmv.toFixed(2)} / {row.refundAmount.toFixed(2)} {row.product.currency}</td><td>{rates.clickThroughRate.toFixed(2)}%</td><td>{rates.orderConversionRate.toFixed(2)}%</td><td>{rates.refundRate.toFixed(2)}%</td></tr>; })}</tbody></table></div>}</div>
      <form action={saveProductPerformance} className="panel form-stack compact-form"><h2>录入商品表现</h2><input type="hidden" name="liveSessionId" value={session.id} /><label>商品<select name="productId" required><option value="">请选择</option>{products.map((product) => <option value={product.id} key={product.id}>{product.name}</option>)}</select></label><label>曝光<input name="impressions" type="number" min="0" defaultValue="0" /></label><label>点击<input name="clicks" type="number" min="0" defaultValue="0" /></label><label>订单<input name="orders" type="number" min="0" defaultValue="0" /></label><label>买家<input name="buyers" type="number" min="0" defaultValue="0" /></label><label>GMV<input name="gmv" inputMode="decimal" defaultValue="0.00" /></label><label>退款金额<input name="refundAmount" inputMode="decimal" defaultValue="0.00" /></label><label>库存<input name="inventory" type="number" min="0" defaultValue="0" /></label><label>佣金<input name="commission" inputMode="decimal" defaultValue="0.00" /></label><button className="button-primary" type="submit">保存表现</button></form>
    </section>
    <section className="dashboard-grid mt-6"><div className="panel span-2"><h2>直播复盘</h2>{session.reviewSummary ? <><div className="detail-meta mt-6"><div><p>累计观看</p><strong>{session.viewers}</strong></div><div><p>峰值在线</p><strong>{session.peakViewers}</strong></div><div><p>新增粉丝</p><strong>{session.newFollowers}</strong></div></div><p className="section-copy whitespace-pre-wrap">{session.reviewSummary}</p></> : <p className="empty-state">完成直播后填写复盘。</p>}</div>{session.status === "COMPLETED" && <form action={saveSessionReview} className="panel form-stack compact-form"><h2>填写复盘</h2><input type="hidden" name="id" value={session.id} /><label>累计观看<input name="viewers" type="number" min="0" defaultValue={session.viewers} /></label><label>峰值在线<input name="peakViewers" type="number" min="0" defaultValue={session.peakViewers} /></label><label>新增粉丝<input name="newFollowers" type="number" min="0" defaultValue={session.newFollowers} /></label><label>实际开始<input name="actualStartsAt" type="datetime-local" /></label><label>实际结束<input name="actualEndsAt" type="datetime-local" /></label><label>复盘结论<textarea name="reviewSummary" required /></label><button className="button-primary" type="submit">保存复盘</button></form>}</section>
    <section className="dashboard-grid mt-6"><div className="panel span-2"><h2>状态历史</h2><ol className="timeline">{session.statusHistory.map((item) => <li key={item.id}><strong>{item.fromStatus ?? "创建"} → {item.toStatus}</strong><span>{item.actor.user.name} · {item.createdAt.toLocaleString("zh-CN")} {item.note ? `· ${item.note}` : ""}</span></li>)}</ol></div><div className="panel"><h2>未结反馈</h2>{session.feedback.length === 0 ? <p className="empty-state">没有未结反馈。</p> : <div className="record-stack">{session.feedback.map((item) => <div className="record-row" key={item.id}><div><h3>{item.title}</h3><small>{item.kind} · {item.category}</small></div><StatusBadge>{item.status}</StatusBadge></div>)}</div>}</div></section>
  </AppShell>;
}
