import { notFound } from "next/navigation";
import { captureMetrics, changeContentStatus, publishContent } from "@/app/actions/work-content";
import { AppShell, Notice, StatusBadge } from "@/components/app-shell";
import { StatusForm } from "@/components/status-form";
import { requirePagePermission } from "@/lib/authorization";
import { db } from "@/lib/db";
import { nextContentStatuses } from "@/lib/work-content/state-machines";

export default async function ContentDetail({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; success?: string }> }) {
  const member = await requirePagePermission(); const { id } = await params; const query = await searchParams;
  const [content, accounts] = await Promise.all([
    db.contentItem.findFirst({ where: { id, organizationId: member.organizationId }, include: { owner: { select: { user: { select: { name: true } } } }, profile: true, video: true, editorial: true, statusHistory: { include: { actor: { select: { user: { select: { name: true } } } } }, orderBy: { createdAt: "desc" } }, publications: { include: { account: true, metricSnapshots: { orderBy: { capturedAt: "desc" } } }, orderBy: { publishedAt: "desc" } } } }),
    db.publishingAccount.findMany({ where: { organizationId: member.organizationId, active: true }, orderBy: [{ channel: "asc" }, { name: "asc" }] }),
  ]);
  if (!content) notFound(); const returnTo = `/content/${content.id}`;
  return <AppShell eyebrow={content.type} title={content.title}><Notice {...query} />
    <section className="dashboard-grid"><div className="panel span-2"><div className="detail-meta"><div><p>负责人</p><strong>{content.owner.user.name}</strong></div><div><p>IP / 栏目</p><strong>{content.profile?.name ?? "未指定"}</strong></div><div><p>状态</p><StatusBadge>{content.status}</StatusBadge></div><div><p>工作量分</p><strong>{content.video?.workloadPoints ?? content.editorial?.workloadPoints ?? 0}</strong></div></div><StatusForm action={changeContentStatus} id={content.id} options={nextContentStatuses(content.status)} returnTo={returnTo} /></div>
      <form action={publishContent} className="panel form-stack compact-form"><h2>登记发布</h2><input name="contentId" type="hidden" value={content.id} /><label>账号<select name="accountId" required><option value="">选择账号</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.channel} · {account.name}</option>)}</select></label><label>发布时间<input name="publishedAt" type="datetime-local" required /></label><label>链接<input name="url" type="url" /></label><button className="button-primary" type="submit">保存发布记录</button></form></section>
    <section className="dashboard-grid mt-6"><div className="panel"><h2>状态历史</h2><ol className="timeline">{content.statusHistory.map((event) => <li key={event.id}><strong>{event.fromStatus ? `${event.fromStatus} → ` : "创建 → "}{event.toStatus}</strong><span>{event.actor.user.name} · {event.createdAt.toLocaleString("zh-CN")}</span></li>)}</ol></div><div className="panel span-2"><h2>发布与指标快照</h2>{content.publications.length === 0 ? <p className="empty-state">尚未登记发布。</p> : <div className="record-stack">{content.publications.map((publication) => <article className="publication" key={publication.id}><div className="section-heading"><div><h3>{publication.account.channel} · {publication.account.name}</h3><p>{publication.publishedAt.toLocaleString("zh-CN")}</p></div>{publication.url && <a className="record-link" href={publication.url} rel="noreferrer" target="_blank">打开内容</a>}</div>{publication.metricSnapshots.length > 0 && <div className="snapshot-strip">{publication.metricSnapshots.map((snapshot) => <div key={snapshot.id}><small>{snapshot.capturedAt.toLocaleDateString("zh-CN")}</small><strong>{snapshot.views.toLocaleString()} 播放</strong><span>{snapshot.likes} 赞 · {snapshot.comments} 评 · {snapshot.shares} 转</span></div>)}</div>}<form action={captureMetrics} className="metrics-form"><input name="publicationId" type="hidden" value={publication.id} /><input name="contentId" type="hidden" value={content.id} /><label>采集时间<input name="capturedAt" type="datetime-local" required /></label><label>播放<input name="views" min="0" type="number" defaultValue="0" /></label><label>点赞<input name="likes" min="0" type="number" defaultValue="0" /></label><label>评论<input name="comments" min="0" type="number" defaultValue="0" /></label><label>转发<input name="shares" min="0" type="number" defaultValue="0" /></label><button className="button-secondary" type="submit">保存快照</button></form></article>)}</div>}</div></section>
  </AppShell>;
}
